### ISSUE TITLE
Publish provider on terraform official site (https://registry.terraform.io/)

### ISSUE THREAD

**Issue by abelal83** [Mastercard/terraform-provider-restapi#123] opened 2021-02-16 15:38 UTC
I noticed several people have forked this repo and published the provider, I think it's likely because this one is not offical published but I think it would be great to do so to at least get recognition.

**Comment by red8888** [comment] 2021-02-16 16:21
I would like to use this provider but dont want to have to ask everyone to manually install it and also don't want to have to manually install it on atlantis which I use to run plan/apply centrally

Is this still in "beta" and thats why its not published to the official repo? I'd like to use this like any other 3rd party provider and have it downloaded automatically

**Comment by DRuggeri** [comment] 2021-03-27 21:39
Hi, folks - I'm going to close this one out as a duplicate of #85 - please do check in over there.

**Closed by DRuggeri** 2021-03-27 21:39 UTC
