### ISSUE TITLE
Can not use Content Length = "0" as header

### ISSUE THREAD

**Issue by m-a-b-u** [Mastercard/terraform-provider-restapi#80] opened 2020-03-17 09:18 UTC
I have the following code and use a **Content-Length = "0"** header in my provider settings. But it´s somehow not used during the API call regarding the output: 
```

#PROVIDER

provider "restapi" {
  uri                  = "https://XXX.dfs.core.windows.net/XXX"
  debug                = true
  write_returns_object = true
  headers = {
    Content-Length = "0"
    Authorization  = "Bearer XXX"
  }

  create_method = "PUT"
}

#RESOURCE DIRECTORY

resource "restapi_object" "directory" {
  path = "/FOLDERX?resource=directory"
  data = "{}"
}
```

Output:
```

Terraform will perform the following actions:

  # restapi_object.directory will be created
  + resource "restapi_object" "directory" {
      + api_data        = (known after apply)
      + api_response    = (known after apply)
      + create_response = (known after apply)
      + data            = jsonencode({})
      + id              = (known after apply)
      + path            = "/FOLDERX?resource=directory"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

restapi_object.directory: Creating...

Error: Unexpected response code '400': {"error":{"code":"ContentLengthMustBeZero","message":"The Content-Length request header must be zero.\nRequestId:f287a78a-b01f-002d-293c-fc5379000000\nTime:2020-03-17T09:13:38.4261545Z"}}

  on foldersync.tf line 17, in resource "restapi_object" "directory":
  17: resource "restapi_object" "directory" {
```

Do you have any ideas why the header is not set correctly?

**Comment by DRuggeri** [comment] 2020-03-23 14:00
It's interesting... I confirmed in the code that it's not setting this header or overwriting it so my assumption is that the golang HTTP client implementation is overwriting it. This actually seems sensible because the data that is set is `{}`, which would therefore be `Content-Length: 2`.

Because this provider is intended to manage a REST-based object, the data field cannot be empty (see #8 - though perhaps with some code this can be managed?)... which would mean that the Content-Length field can never be 0 if the golang HTTP client is forcing the header based on the actual data length.

**Comment by DRuggeri** [comment] 2020-05-18 17:53
Just following up on this... Given that the provider must have data defined, I don't think it will be possible to do what you're describing. Is there an expected action we can take?

**Comment by DRuggeri** [comment] 2020-06-26 14:47
Closing this out for now, but if there's more to add, please feel free to reopen discussion here.

**Closed by DRuggeri** 2020-06-26 14:47 UTC
