### ISSUE TITLE
Support for GET returning array of objects rather than specific object

### ISSUE THREAD

**Issue by robertgates55** [Mastercard/terraform-provider-restapi#58] opened 2019-09-03 09:46 UTC
Thanks for this provider - been using for a day or so now and it's nicely thought out.

I'm working with the gitea API, and trying to add a user to a team. The only related API methods for this are:
`PUT /team/0/members/robertgates55` - to add a user object to team `0`
`DELETE  /team/0/members/robertgates55` - to remove user object from team `0`
`GET /team/0/members` - returns an array of the user objects in that team

Is there any way I can work with this API? I've already set `create_method = "PUT"` in the provider, and am setting the `object_id` manually (as the `PUT` doesn't return the object it creates); but since theres no `GET /team/0/members/robertgates55` method available, we obviously can't work out whether my `object_id` is a member of the team.

Any ideas?

**Comment by DRuggeri** [comment] 2019-09-19 17:57
Hi, @robertgates55, initially, I thought you could find the user using the datasource, but the problem is that without a GET on the path `/team/0/members/robertgates55`, it will fail after the first run. After thinking about it, I'm afraid that this API just doesn't offer the methods needed.

POTENTIALLY... you can try making the `read_method` PUT? If that method is idempotent on the API, I guess it *may* work.

**Comment by lurkingsystemsdude** [comment] 2020-02-24 21:32
I'm having a similar conundrum, albeit with a totally different REST application; I'm using Netbox (https://github.com/netbox-community/netbox)  to model my infrastructure, and I want to ask Netbox "give me a list of all servers of role X in datacenter Y, rack Z" and parse the results. I can ask this with a GET query like "/api/dcim/devices/?q=&rack_id=513&role=server-type&site=mysite"
and the resulting array will contain multiple servers. 

When I try to do this with a data source like this:
data "restapi_object" "af12-iad2_devices" {
  path = "/api/dcim/devices/"
  query_string = "site=iad2&rack_id=513&role=server-game"
  search_key = "site/name"
  search_value = "iad2"
  results_key = "results"
}

... only the first item in the array will be matched.  Is there a way to get them all?


'{
"count": 31,
"next": null,
"previous": null,
"results": [
{28 items},
{28 items},
{28 items},
{28 items},
{28 items},
{
"id": 35289,
"name": "gs05b-af12-iad2",
"display_name": "gs05b-af12-iad2",
"device_type": {
"id": 97,
"url": "https://netbox.simulprod.com/api/dcim/device-types/97/?format=json",

**Comment by DRuggeri** [comment] 2020-03-02 18:21
Hi, @lurkingsystemsdude;
I'm not really opposed to the idea, per se, but the goal of this provider is to manage individual resources (which is why search results return just one). Perhaps the better tool for what you are attempting to accomplish is the [External ](https://www.terraform.io/docs/providers/external/data_source.html) datasource coupled with some curl-ing?

**Comment by lurkingsystemsdude** [comment] 2020-03-04 22:36
Thanks @DRuggeri ! I will take a closer look at the External datasource. In my case I really am just looking to pull some other data into Terraform (not modify it YET), and Netbox already does expose it as JSON, so you're probably right that some curl-ing would do the trick.  I may circle back to this one when I'm ready to try modifying objects once I know which ones they are.

**Comment by DRuggeri** [comment] 2020-03-23 14:09
OK, cool. I'll go ahead and close this issue for now, but feel free to open it back up with more details as you experiment!

**Closed by DRuggeri** 2020-03-23 14:09 UTC

**Comment by Nuru** [comment] 2020-04-23 00:27
I'm having a similar issue. For some reason, the server does not have a `GET /items/{id}` endpoint to retrieve a single item. It does, however, have a search-like endpoint, so I can `GET /items/?id={id}` which returns one item, but that item is in an array, since it is a search endpoint. So I get 
```
Error: json: cannot unmarshal array into Go value of type map[string]interface {}
```

The resource needs to have some of the same extras that the datasource has in order to find its object in its response. 

Also, it needs to deal with sensitive data not being returned in the GET. If you GET a user, you will not get the user's password, but that doesn't mean it needs to be reset.
