### ISSUE TITLE
Terraform 0.13 ?

### ISSUE THREAD

**Issue by cvalentin-adeo** [Mastercard/terraform-provider-restapi#95] opened 2020-09-04 09:35 UTC
Hi, you can upload provider in terraform public repository ? :)

**Comment by mariusvniekerk** [comment] 2020-09-04 16:39
Over here for reference https://registry.terraform.io/

**Comment by cvalentin-adeo** [comment] 2020-09-08 08:53
In 0.13, registry is mandatory :/ 
If provider is not in public registry (or in-house), provider is unusable :'(

**Comment by shanedabes** [comment] 2020-09-19 00:59
That's not entirely true, you can still install the providers manually, the file location structure has just changed.

https://www.hashicorp.com/blog/automatic-installation-of-third-party-providers-with-terraform-0-13

I'm still entirely for getting this provider in the registry, installation becomes so much easier.

**Comment by DRuggeri** [comment] 2020-09-21 16:53
Hi there, all. Yes, that's definitely part of the plan. I need to set aside some time to focus on this. I'll go ahead and close this issue as a duplicate of #85 where I plan to continue tracking this.

**Closed by DRuggeri** 2020-09-21 16:53 UTC
