### ISSUE TITLE
Unable to view any output

### ISSUE THREAD

**Issue by niraj8241** [Mastercard/terraform-provider-restapi#90] opened 2020-07-18 18:03 UTC
Hi,

I am trying to do some GETS on an API which returns JSON's inside a list. The output query that I am trying to use is as below 

```
data "restapi_object" "test" {
  path = "/api/credentials"
  search_value = "test-creds"
  search_key = "credentials_name"
}
```

```output "test1" {
  value = jsondecode(data.restapi_object.test.api_response)
}
```

What am I doing wrong?
Niraj

**Comment by gangofnuns** [comment] 2020-07-19 05:33
So to answer your question, Niraj8241 -- I think you may need the results_key to retrieve your array. 

> Error: api_object.go: The results of a GET to '/users/foo_user' did not return an array. 
> It is a 'map[string]interface {}'. Perhaps you meant to add a results_key?

> Alas, it looks like golang datatypes are leaking in.  From the docs:
 
> results_key (string, required): When issuing a GET to the path, this JSON key is used to locate 
> the results array.  The format is 'field/field/field'. Example: 'results/values'. If omitted, it is 
> assumed the results coming back are already an array and are to be used exactly as-is

> So the data resource expects a '/' separated, path-like string which is used to navigate to the desired 
> array within the nested data returned from the API.   Implying that you can only search for arrays.   
> AFAICT, looking for anything else (such as a user record) will cause an error. 


> Hi,
> 
> I am trying to do some GETS on an API which returns JSON's inside a list. The output query that I am trying to use is as below
> 
> ```
> data "restapi_object" "test" {
>   path = "/api/credentials"
>   search_value = "test-creds"
>   search_key = "credentials_name"
> }
> ```
> 
> ```
>   value = jsondecode(data.restapi_object.test.api_response)
> }
> ```
> 
> What am I doing wrong?
> Niraj

**Comment by niraj8241** [comment] 2020-07-22 16:35
So it seems like the results that I am getting doesn't have a results key
The result looks something like this

[
    {
        "credentials_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "account_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "aws_credentials": {
            "sts_role": {
                "role_arn": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "external_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            }
        },
        "credentials_name": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "creation_time": xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    }
]

**Comment by DRuggeri** [comment] 2020-09-21 15:30
Hi there, @niraj8241. Can you help elaborate a bit more on what is going wrong? Your configuration appears correct. Since `results_key` is not set, and the data that is coming back is already an array, you don't need to change the values.

I do see that the `credentials_name` is properly set as the `search_key` and I assume the `search_value` is coming up, right?

Perhaps setting `TF_LOG=TRACE` in your environment might identify what is happening from a raw HTTP request/response level to help troubleshoot?

**Comment by niraj8241** [comment] 2020-10-11 20:57
So, I did some debugging around and I can see that when using debug(export TF_LOG=1) mode, the result is available as an array. But I am still unable to view any output. This is my entire config:

`provider "restapi" {
  uri                  = "https://xxxxxxxxxxxxxxxxxxxxx/api/2.0/accounts/"
  debug                = true
  write_returns_object = true
  username             = "xxxxxxxxxxxxxxx"
  password             = "xxxxxxxxxxxxxxx"
  id_attribute         = "account_id"
}

data "restapi_object" "test" {
  path        = "/3e9cdbb7-87d4-4f50-ad89-0b8f01c8081f/workspaces"
  search_value = "dev"
  search_key   = "workspace_name"
}

output "test1" {
  value = data.restapi_object.test.api_data
}`

`[
    {
        "workspace_id": xxxxxxxxxxxxxx
        "workspace_name": "dev",
        "aws_region": "xxxxxxxxx",
        "creation_time": xxxxxxxxxx
        "deployment_name": "dev",
        "workspace_status": "RUNNING",
        "account_id": "xxxxxxxxxxxxxxxxxxxxx",
        "credentials_id": "xxxxxxxxxxxxxxxxxxxxx",
        "storage_configuration_id": "xxxxxxxxxxxxxxxxxxxxx",
        "workspace_status_message": "Workspace is running.",
        "network_id": "xxxxxxxxxxxxxxxxxxxxx",
        "pricing_tier": "xxxxxxxxxx"
    }
]`

**Comment by DRuggeri** [comment] 2020-10-29 17:41
I'm sorry, but I'm still not sure what you are seeing. Are you getting errors, or does no output get printed to screen? I ask because the provider will throw an error if it cannot find the item you are searching for... so it makes me think it's finding the result, but maybe it's not printing on the screen like you would expect?

If you examine the debug output, you'll be able to see the response that comes back and the provider will also log whether it finds the key it is looking for.

**Comment by niraj8241** [comment] 2020-11-16 07:15
So, when the problem is that I am unable to print any output. I was able to see the results array in my debug terraform output which confirms that the config is right and the only problem I have is while printing output.

**Comment by DRuggeri** [comment] 2020-12-28 21:32
I see what you mean now. An `output` is not actually printed - it serves as the [output of a module](https://www.terraform.io/docs/configuration/outputs.html). I think that this is expected behavior with terraform. Given that you're seeing your results coming back, it looks like you're in good shape.

With that in mind, I will close this one, but please do let me know if I misunderstand what the expectation is.

**Closed by DRuggeri** 2020-12-28 21:32 UTC
Labels: question
