### ISSUE TITLE
 Object ID is not set, but *may* have been created. This should never happen

### ISSUE THREAD

**Issue by vrvenky1407** [Mastercard/terraform-provider-restapi#46] opened 2019-07-04 19:58 UTC
Hi

  I was trying to create Host record in infoblox using the provider. The Host record gets created but my terraform apply fails. 

restapi_object.allocate_ip: Creating...
  api_data.%:  "" => "<computed>"
  create_path: "" => "/record:host"
  data:        "" => "{\"ipv4addrs\":[{\"ipv4addr\":\"10.7.8.7\"}],\"name\":\"tfhosttest.fisdev.local\"}\n"
  path:        "" => "/record:host"

Error: Error applying plan:

1 error(s) occurred:

* restapi_object.allocate_ip: 1 error(s) occurred:

* restapi_object.allocate_ip: Internal validation failed. Object ID is not set, but *may* have been created. This should never happen!

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

 tf config 
-----------
resource "restapi_object" "allocate_ip" {
  path = "/record:host"
  create_path = "/record:host"
  data = "${file("add_host_record.json")}"
}

add_host_record.json
-----------------------
{"ipv4addrs":[{"ipv4addr":"10.7.8.7"}],"name":"tfhosttest.fisdev.local"}

provider.tf
------------
provider "restapi" {
  uri = "https://myinfoblox.dev.local/wapi/v2.6/"
  insecure = true
  username = "admin"
  password = "xxxxxxxxxxxx"
  write_returns_object = true
  create_method = "POST"
  update_method = "POST"
  create_returns_object = true
  debug                = true
}

Please let me know what I need to do to fix this problem.

**Comment by DRuggeri** [comment] 2019-07-05 19:04
Hi, @vrvenky1407. It looks like you're missing an `id_attribute`. Since that isn't set, the provider assumes that `id` will be one of the attributes returned. In this case, that doesn't exist, so there's no value.

For Infoblox, I believe the real object ID is `_ref`. Note that this provider will attempt to use the id in subsequent requests in the path, so you probably also need to set `path` to be `record:host` so it doesn't try to interpolate the ID into the path.

**Comment by vrvenky1407** [comment] 2019-07-06 11:16
Hi

  I set id_attribute to "_ref"  and  also set the path but still I am getting the same error.

  Please find below the portion of Terraform apply log below

restapi_object.allocate_ip: Creating...
  api_data.%:   "" => "<computed>"
  create_path:  "" => "/record:host"
  data:         "" => "{ \"name\":\"testtfip.fisdev.local\",\n    \"ipv4addrs\":[\n       {\n          \"ipv4addr\":\"func:nextavailableip:10.7.8.0/23\"\n       }\n    ]\n}\n\n"
  destroy_path: "" => "/record:host"
  id_attribute: "" => "_ref"
  path:         "" => "/record:host"
  read_path:    "" => "/record:host"
  update_path:  "" => "/record:host"
2019/07/06 07:06:50 [TRACE] root: eval: *terraform.EvalApply
2019/07/06 07:06:50 [DEBUG] apply: restapi_object.allocate_ip: executing Apply
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:50 common.go: make_api_object routine called for id ''
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:50 create_path: /record:host
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:50 resource_api_object.go: Create routine called. Object built:
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: id:
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: get_path: /record:host
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: post_path: /record:host
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: put_path: /record:host
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: delete_path: /record:host
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: debug: false
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: data: (map[string]interface {}) (len=2) {
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0:  (string) (len=4) "name": (string) (len=21) "testtfip.fisdev.local",
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0:  (string) (len=9) "ipv4addrs": ([]interface {}) (len=1 cap=1) {
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0:   (map[string]interface {}) (len=1) {
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0:    (string) (len=8) "ipv4addr": (string) (len=32) "func:nextavailableip:10.7.8.0/23"
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0:   }
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0:  }
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: }
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0:
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: api_data: (map[string]interface {}) {
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: }
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0:
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0:
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:50 api_client.go: method='POST', path='/record:host', full uri (derived)='https://labipam.fis.lab/wapi/v2.6/record:host', data='{"ipv4addrs":[{"ipv4addr":"func:nextavailableip:10.7.8.0/23"}],"name":"testtfip.fisdev.local"}'
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:50 api_client.go: Sending HTTP request to https://labipam.fis.lab/wapi/v2.6/record:host...
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:50 api_client.go: Request headers:
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:50 api_client.go:   Content-Type: application/json
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:50 api_client.go:   Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxx
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:50 api_client.go: BODY:
2019-07-06T07:06:50.642-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:50 {"ipv4addrs":[{"ipv4addr":"func:nextavailableip:10.7.8.0/23"}],"name":"testtfip.fisdev.local"}
2019-07-06T07:06:51.469-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:51 api_client.go: Response code: 201
2019-07-06T07:06:51.469-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:51 api_client.go: Response headers:
2019-07-06T07:06:51.469-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:51 api_client.go:   Content-Type: application/json
2019-07-06T07:06:51.469-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:51 api_client.go:   Date: Sat, 06 Jul 2019 11:06:50 GMT
2019-07-06T07:06:51.469-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:51 api_client.go:   Cache-Control: no-cache, no-store
2019-07-06T07:06:51.469-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:51 api_client.go:   Pragma: no-cache
2019-07-06T07:06:51.469-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:51 api_client.go:   Set-Cookie: ibapauth="client=API,group=infoblox_devops,ctime=1562411211,timeout=2700,mtime=1562411211,ip=10.7.8.4,auth=AD,user=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"; httponly; Path=/
2019-07-06T07:06:51.469-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: 2019/07/06 07:06:51 api_client.go: BODY:
2019-07-06T07:06:51.469-0400 [DEBUG] plugin.terraform-provider-restapi_v1.9.0: "record:host/ZG5zLmhvc3QkLl9kZWZhdWx0LmxvY2FsLmZpc2Rldi50ZXN0dGZpcA:testtfip.fisdev.local/FIS_IPAM"
2019/07/06 07:06:51 [TRACE] root: eval: *terraform.EvalWriteState
2019/07/06 07:06:51 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2019/07/06 07:06:51 [TRACE] root: eval: *terraform.EvalIf
2019/07/06 07:06:51 [TRACE] root: eval: *terraform.EvalWriteState
2019/07/06 07:06:51 [TRACE] root: eval: *terraform.EvalWriteDiff
2019/07/06 07:06:51 [TRACE] root: eval: *terraform.EvalApplyPost
2019/07/06 07:06:51 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* restapi_object.allocate_ip: Internal validation failed. Object ID is not set, but *may* have been created. This should never happen!
2019/07/06 07:06:51 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* restapi_object.allocate_ip: Internal validation failed. Object ID is not set, but *may* have been created. This should never happen!
2019/07/06 07:06:51 [TRACE] [walkApply] Exiting eval tree: restapi_object.allocate_ip
2019/07/06 07:06:51 [TRACE] dag/walk: upstream errored, not walking "output.allocated_ip"
2019/07/06 07:06:51 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2019/07/06 07:06:51 [TRACE] dag/walk: upstream errored, not walking "provider.restapi (close)"
2019/07/06 07:06:51 [TRACE] dag/walk: upstream errored, not walking "root"
2019/07/06 07:06:51 [TRACE] Preserving existing state lineage "59ca2c4e-c84e-3e93-d392-e0dd802d043f"
2019/07/06 07:06:51 [TRACE] Preserving existing state lineage "59ca2c4e-c84e-3e93-d392-e0dd802d043f"
2019/07/06 07:06:51 [TRACE] Preserving existing state lineage "59ca2c4e-c84e-3e93-d392-e0dd802d043f"
2019/07/06 07:06:51 [TRACE] Preserving existing state lineage "59ca2c4e-c84e-3e93-d392-e0dd802d043f"

Error: Error applying plan:

1 error(s) occurred:

* restapi_object.allocate_ip: 1 error(s) occurred:

* restapi_object.allocate_ip: Internal validation failed. Object ID is not set, but *may* have been created. This should never happen!

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

My terraform config file

resource "restapi_object" "allocate_ip" {
  path = "/record:host"
  create_path = "/record:host"
  read_path = "/record:host"
  destroy_path = "/record:host"
  update_path = "/record:host"
  id_attribute = "_ref"
  data = "${file("allocate_ip.json")}"
}

So where is the issue. Please advise.

**Comment by vrvenky1407** [comment] 2019-07-06 15:54
Hi

After changing the create_path with "/record:host?_return_fields=ipv4addrs"  it worked.

I don't know whether it is right way.  But it worked and I have the _ref field with the object which is created.

Please see below the last part of the Terraform apply.

restapi_object.allocate_ip: Creating...
  api_data.%:   "" => "<computed>"
  create_path:  "" => "/record:host?_return_fields=ipv4addrs"
  data:         "" => "{ \"name\":\"testtfip.fisdev.local\",\n    \"ipv4addrs\":[\n       {\n          \"ipv4addr\":\"func:nextavailableip:10.7.8.0/23\"\n       }\n    ]\n}\n\n"
  destroy_path: "" => "/record:host"
  id_attribute: "" => "_ref"
  path:         "" => "/record:host"
  read_path:    "" => "/record:host"
  update_path:  "" => "/record:host"
restapi_object.allocate_ip: Creation complete after 1s (ID: record:host/ZG5zLmhvc3QkLl9kZWZhdWx0Lmx...0dGZpcA:testtfip.fisdev.local/FIS_IPAM)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

This is my terraform configuration

resource "restapi_object" "allocate_ip" {
  path = "/record:host"
  create_path = "/record:host?_return_fields=ipv4addrs"
  read_path = "/record:host"
  destroy_path = "/record:host"
  update_path = "/record:host"
  id_attribute = "_ref"
  data = "${file("allocate_ip.json")}"
}

Let me know if it is fine.

**Comment by cnguyenp** [comment] 2019-07-12 18:49
I have question on your setup. Since you have create_path, read_path, update_path in one resource, when this code runs, does it execute all of the POST, GET, and PUT at the same time? How do you handle PUT with the ID return from GET?

**Comment by DRuggeri** [comment] 2019-07-12 23:16
I can see the confusion. No, it will only use the method defined for that action. For example, if terraform decides it needs to create an object, this provider will use POST (by default). The object's ID should come back from the API or be in the data structure. If terraform then decides it needs to modify the object sometime later, it will use PUT to the path of the object with updated data.

**Comment by cnguyenp** [comment] 2019-07-13 00:18
Thank you @DRuggeri. 
I got it.
- In v1.9.0, I have to use `update_method:PUT` and `create_method:PUT` and `create_path`, and it runs without problem. 
- On v1.9.2: 
- When I  use `update_method: PUT` in the provider and `update_path` in the resource. It returns 404 status. 
- However, if i use `update_method:PUT` and `create_method:PUT` in provider and `create_path` in the resource, it will work for the first run. On the second run it returns 404. 

- What am I missing on this PUT request?

case 1: provider:  PUT and resource : update_path
![update_path_on_put ](https://user-images.githubusercontent.com/35930087/61164160-c9a52000-a4c7-11e9-8e2b-db8bb2ce2083.png)

case 2: this is working on V1.9.0 without problem, but it fails on v1.9.2 on the second run
![create_pathon_2 puts](https://user-images.githubusercontent.com/35930087/61164195-20125e80-a4c8-11e9-9506-0627a37d1bc1.png)

**Comment by DRuggeri** [comment] 2019-07-17 19:40
Hi, @cnguyenp - can you help keep the project clean by using just one issue? At first I thought #50 is a duplicate of this one, but I think you've maybe changed topics without me realizing. Can you clarify if these are indeed separate issues?

**Comment by cnguyenp** [comment] 2019-07-17 20:02
this is the same issue #50 . Sorry for the confusion.

**Comment by DRuggeri** [comment] 2019-07-24 18:58
Closing as duplicate

**Closed by DRuggeri** 2019-07-24 18:58 UTC
